In [11]:
# import  os
# num_cores = "1"
# os.environ["OPENBLAS_NUM_THREADS"] = num_cores
# os.environ["OMP_NUM_THREADS"] = num_cores
# os.environ["MKL_NUM_THREADS"] = num_cores

In [12]:
import sys
sys.path.append('../')

import numpy as np
import scipy.sparse as ssp
import matplotlib.pyplot as plt
import qutip as qt
import scqubits as scq
from matplotlib.colors import LogNorm
from tqdm import tqdm
from qutip.qip.operations import rz, cz_gate
import cmath
from sympy import symbols
from scipy.sparse.linalg import eigsh
import utils_2Q_gate_zp as ut
from joblib import Parallel, delayed
from IPython.display import display, Math
# ut.set_fig_font() ### Set various sizes in plotting
import networkx as nx
from multiprocessing import Pool
import pandas as pd

In [13]:
truc1, truc_tot, charge_pick  = 300, 1000, True
normalize = True
folder = f'../../data/3ncut_two_zeropi/truc1={truc1}_truc2={truc_tot}_pick={charge_pick}/'
eval_tot = pd.read_csv(folder+ 'eval_tot.txt').to_numpy().flatten()
n_theta0_dress = pd.read_csv(folder+ 'n_theta0_dress.txt').to_numpy()
n_theta1_dress = pd.read_csv(folder+ 'n_theta1_dress.txt').to_numpy()
hspace_full = pd.read_csv(folder+ 'hspace_full.txt').to_numpy().flatten().tolist()

In [14]:
truc_tot_2 = 500
truc_list = np.arange(truc_tot_2)
hspace_full = hspace_full[:truc_tot_2]
eval_tot = eval_tot[:truc_tot_2]

n_theta0_dress = ut.truncate_2(n_theta0_dress, truc_list)
n_theta1_dress = ut.truncate_2(n_theta1_dress, truc_list)
# print(np.shape(n_theta0_dress))
logi_state = ['0-0', '0-2', '2-0', '2-2']

# core_states = logi_state + ['4-5']
# idx_0 = hspace_full.index('0-2')
# idx_1 = hspace_full.index('2-2')
# idx_2 = hspace_full.index('4-5')

core_states = logi_state + ['8-2']
idx_0 = hspace_full.index('0-2')
idx_1 = hspace_full.index('2-2')
idx_2 = hspace_full.index('8-2')

W_0_2 = eval_tot[idx_2] - eval_tot[idx_0]
W_1_2 = eval_tot[idx_2] - eval_tot[idx_1]
print('E_45: W_0_2 = ', np.round(2*np.pi*W_0_2, 3), ', W_1_2 = ', np.round(2*np.pi*W_1_2, 3))

E_45: W_0_2 =  45.546 , W_1_2 =  23.753

### Truncation Estimate

In [15]:
drive_term = n_theta0_dress
max_n_ij = np.max(np.abs(drive_term.full()))
A = 0.02
######
# max_n_ij = np.max(drive_term) # Normalize based on n
population_rate = np.zeros((truc_tot, truc_tot), dtype=np.complex128)
population_rate_log = np.zeros((truc_tot, truc_tot), dtype=np.complex128)
rabi_df = []
G = nx.DiGraph()
for i, s_i in enumerate(hspace_full):
    for j, s_j in enumerate(hspace_full):
        if i < j:
            n_ij = np.abs(drive_term[i, j])
            if normalize:
                n_ij *= n_ij/max_n_ij
            # normalization =  n_ij/max_n_ij
            delta_1 = abs(W_0_2 - (eval_tot[j] - eval_tot[i]))
            delta_2 = abs(W_1_2 - (eval_tot[j] - eval_tot[i]))

            population_rate[i,j] = ((A*n_ij)**2) / ((A*n_ij)**2 + delta_1**2) + ((A*n_ij)**2) / ((A*n_ij)**2 + delta_2**2)
            if population_rate[i,j] > 0:
                population_rate_log[i, j] = -np.log(population_rate[i,j])
                G.add_edge(s_i, s_j, weight=population_rate_log[i, j]) # Construct the graph

    rabi_df.append({"order": i, "i": s_i})
rabi_df = pd.DataFrame(rabi_df)
rabi_df.index = rabi_df["i"]
print('shape(population_rate_log)=', np.shape(population_rate_log))
# rabi_df

shape(population_rate_log)= (1000, 1000)

In [16]:
def shortest_path_to_core(target):
    shortest_path = ""
    shortest_path_len = np.inf
    for source in core_states[:-1]:
        if nx.has_path(G, source, target):
            path = nx.shortest_path(G, source=source, target=target,
                                    weight="weight")
            path_len = nx.shortest_path_length(G, source=source, target=target,
                                                weight="weight")
        if path_len < shortest_path_len:
            shortest_path_len = path_len
            shortest_path = ",".join([str(x) for x in path])
    return target, (shortest_path_len, shortest_path)

cutoff = 2
def all_path_to_core(target):
    path_tot = []
    if target in core_states:
        weight_tot = 1
    else:
        weight_tot = 0
        for source in core_states:
            for path in nx.all_simple_paths(G, source, target, cutoff=cutoff):
                weight_tot += np.exp( - nx.path_weight(G, path,'weight') )
                path_tot.append(path)
    return target, (weight_tot, path_tot)

### All path

In [17]:
# Find all_path_to_core
pool = Pool(processes=150)
shortest_path = {}
rabi_df["path"] = ""
rabi_df["path_len"] = 1.0
for idx, path in tqdm(pool.imap_unordered(all_path_to_core, hspace_full),
                total=truc_tot):
    shortest_path[idx[0]] = path
    rabi_df.at[idx, "path"] = path[1]
    rabi_df.at[idx, "path_len"] = path[0]

df_all = rabi_df.sort_values("path_len", ascending=False)
print('all_path -- cutoff=', cutoff)
df_all.iloc[:30]

  0%|          | 0/1000 [00:00<?, ?it/s]FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '(3.959674672888022e-05+0j)' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
 50%|█████     | 500/1000 [00:01<00:01, 291.17it/s]

all_path -- cutoff= 2

,order,i,path,path_len
i,,,,
0-0,0,0-0,[],1.000000e+00+0.000000e+ 00j
2-2,13,2-2,[],1.000000e+00+0.000000e+ 00j
0-2,3,0-2,[],1.000000e+00+0.000000e+ 00j
2-0,4,2-0,[],1.000000e+00+0.000000e+ 00j
8-2,37,8-2,[],1.000000e+00+0.000000e+ 00j
12-2,64,12-2,"[[0-0, 0-1, 12-2], [0-0, 1-0, 12-2], [0-0, 0-5...",1.973147e-04+0.000000e+ 00j
4-9,63,4-9,"[[0-0, 0-1, 4-9], [0-0, 1-0, 4-9], [0-0, 0-5, ...",4.604333e-05+0.000000e+ 00j
1-2,11,1-2,"[[0-0, 1-2], [0-2, 1-2], [2-0, 1-2]]",4.369682e-05+0.000000e+ 00j
1-0,2,1-0,"[[0-0, 1-0]]",3.959675e-05+0.000000e+ 00j
5-2,27,5-2,"[[0-0, 5-2], [0-2, 5-2], [2-0, 5-2], [2-2, 5-2]]",3.553933e-05+0.000000e+ 00j
5-0,10,5-0,"[[0-0, 5-0], [0-2, 5-0], [2-0, 5-0]]",2.842682e-05+0.000000e+ 00j
8-5,68,8-5,"[[0-0, 0-1, 8-5], [0-0, 1-0, 8-5], [0-0, 0-5, ...",3.664538e-06+0.000000e+ 00j
22-2,117,22-2,"[[0-0, 0-1, 22-2], [0-0, 1-0, 22-2], [0-0, 0-5...",2.728876e-06+0.000000e+ 00j
9-2,46,9-2,"[[0-0, 0-1, 9-2], [0-0, 1-0, 9-2], [0-0, 0-5, ...",1.280341e-06+0.000000e+ 00j
2-1,9,2-1,"[[0-0, 2-1], [0-2, 2-1], [2-0, 2-1]]",1.220351e-06+0.000000e+ 00j
5-8,62,5-8,"[[0-0, 0-1, 5-8], [0-0, 1-0, 5-8], [0-0, 0-5, ...",6.991466e-07+0.000000e+ 00j
5-5,48,5-5,"[[0-0, 0-1, 5-5], [0-0, 1-0, 5-5], [0-0, 0-5, ...",4.816363e-07+0.000000e+ 00j
0-1,1,0-1,"[[0-0, 0-1]]",3.948840e-07+0.000000e+ 00j
34-2,202,34-2,"[[0-0, 0-1, 34-2], [0-0, 1-0, 34-2], [0-0, 0-5...",3.920092e-07+0.000000e+ 00j
2-5,24,2-5,"[[0-0, 2-5], [0-2, 2-5], [2-0, 2-5], [2-2, 2-5]]",2.246309e-07+0.000000e+ 00j
13-2,70,13-2,"[[0-0, 0-1, 13-2], [0-0, 1-0, 13-2], [0-0, 0-5...",1.814635e-07+0.000000e+ 00j
8-0,14,8-0,"[[0-0, 8-0], [0-2, 8-0], [2-0, 8-0], [2-2, 8-0]]",1.245261e-07+0.000000e+ 00j
0-5,8,0-5,"[[0-0, 0-5], [0-2, 0-5], [2-0, 0-5]]",9.579649e-08+0.000000e+ 00j
30-2,190,30-2,"[[0-0, 0-1, 30-2], [0-0, 1-0, 30-2], [0-0, 0-5...",4.104405e-08+0.000000e+ 00j
1-4,15,1-4,"[[0-0, 1-4], [0-2, 1-4], [2-0, 1-4], [2-2, 1-4]]",3.628092e-08+0.000000e+ 00j
20-5,184,20-5,"[[0-0, 0-1, 20-5], [0-0, 1-0, 20-5], [0-0, 0-5...",2.352349e-08+0.000000e+ 00j
15-5,123,15-5,"[[0-0, 0-1, 15-5], [0-0, 1-0, 15-5], [0-0, 0-5...",1.405866e-08+0.000000e+ 00j
4-2,22,4-2,"[[0-0, 0-1, 4-2], [0-0, 1-0, 4-2], [0-0, 0-5, ...",4.628958e-09+0.000000e+ 00j
15-2,73,15-2,"[[0-0, 15-2], [0-2, 15-2], [2-0, 15-2], [2-2, ...",4.439957e-09+0.000000e+ 00j
24-2,122,24-2,"[[0-0, 0-1, 24-2], [0-0, 1-0, 24-2], [0-0, 0-5...",3.779320e-09+0.000000e+ 00j

In [ ]:
num_state = 100
df_all_truc = df_all.iloc[:num_state].sort_values("order", ascending=True)
print(f'state_all ({num_state}/{truc_tot_2}) :')
data = df_all_truc['i']
dim = 10
for i in range(0, len(data), dim):  # Step size of 10
    print(", ".join(f"'{x}'" for x in data[i:i + dim]), ',')

index_all = [hspace_full.index(i) for i in df_all_truc['i']]
print(index_all)

state_all 100 :
'0-0', '0-1', '1-0', '0-2', '2-0', '4-0', '1-1', '0-5', '2-1', '5-0' ,
'1-2', '2-2', '8-0', '1-4', '4-1', '2-4', '9-0', '1-5', '5-1', '4-2' ,
'2-5', '1-8', '12-0', '5-2', '8-1', '4-4', '13-0', '15-0', '9-1', '8-2' ,
'5-4', '4-5', '0-21', '18-0', '9-2', '5-5', '4-8', '1-13', '20-0', '8-4' ,
'2-12', '15-1', '5-8', '4-9', '12-2', '9-4', '8-5', '25-0', '13-2', '26-0' ,
'1-18', '15-2', '5-9', '4-12', '18-1', '9-5', '5-12', '15-4', '18-2', '2-21' ,
'8-9', '1-25', '9-8', '12-5', '20-2', '5-16', '22-2', '13-5', '24-2', '15-5' ,
'9-9', '18-4', '12-8', '25-2', '26-2', '9-12', '12-9', '45-0', '18-5', '13-9' ,
'20-5', '22-5', '30-2', '25-4', '15-9', '33-2', '34-2', '35-2', '37-2', '25-5' ,
'26-5', '26-8', '24-9', '30-5', '44-2', '45-2', '50-2', '56-2', '45-5', '64-2' ,
[0, 1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16, 18, 19, 20, 21, 22, 24, 25, 26, 27, 30, 31, 32, 33, 36, 37, 38, 39, 44, 45, 46, 48, 50, 51, 52, 53, 56, 60, 62, 63, 64, 66, 68, 69, 70, 71, 72, 73, 75, 76, 79, 81, 97, 98, 102, 104, 105, 107, 108, 111, 115, 116, 117, 118, 122, 123, 129, 130, 134, 142, 149, 157, 160, 162, 164, 176, 184, 186, 190, 191, 192, 198, 202, 205, 215, 226, 230, 280, 282, 283, 293, 298, 336, 398, 440, 463]

In [37]:
all_82_eli = [
'0-0', '0-2', '2-0', '8-2', '2-2', '12-2', '1-2', '1-0', '5-2', '4-9' ,
'5-0', '8-5', '22-2', '2-1', '9-2', '5-8', '0-1', '5-5', '34-2', '2-5' ,
'13-2', '8-0', '0-5', '1-4', '30-2', '20-5', '15-5', '4-2', '15-0', '15-2' ,
'1-1', '26-5', '8-9', '24-2', '26-2', '25-2', '9-0', '20-2', '4-5', '12-5' ,
'4-0', '5-1', '18-2', '12-0', '37-2', '9-4', '9-5', '1-5', '13-0', '35-2' ,
'13-9', '8-1', '20-0', '4-1', '9-1', '33-2', '18-5', '9-9', '12-8', '1-13' ,
'18-0', '9-8', '5-4', '1-8', '0-21', '5-16', '15-1', '5-12', '26-0', '25-4' ,
'1-25', '9-12', '22-5', '18-4', '4-4', '1-18', '64-2', '2-4', '5-9', '15-4' ,
'12-9', '13-5', '44-2', '45-5', '2-12', '4-12', '45-0', '18-1', '4-8', '8-4' ,
'15-9', '25-5', '24-9', '2-21', '50-2', '45-2', '12-1', '0-8', '26-8', '12-4' ,
'25-0', '18-8', '28-2', '1-9', '2-8', '35-0', '50-5', '20-4', '41-0', '46-2' ,
'39-0', '25-1', '0-4', '22-0', '33-0', '41-2', '22-9', '34-5', '8-18', '39-2' ,
'22-4', '59-2', '58-2', '60-2', '2-25', '56-2', '4-13', '54-2', '50-0', '30-5' ,
'13-1', '26-9', '20-9', '34-9', '15-8', '4-16', '4-21', '8-12', '2-30', '33-5' ,
'51-2', '35-4', '24-5', '59-0', '1-21', '0-25', '2-9', '56-0', '65-0', '41-1' ,
'35-5', '24-0', '20-1', '30-4', '18-9', '13-8', '65-2', '9-16', '46-5', '25-8' ,
'51-5', '2-26', '0-30', '28-1', '46-0', '9-13', '0-12', '0-24', '28-5', '34-0' ,
'22-8', '13-4', '33-12', '5-18', '4-24', '0-45', '41-5', '39-5', '34-1', '12-20' ,
'37-5', '24-1', '30-1', '12-12', '0-18', '22-1', '0-9', '37-0', '44-0', '13-12' ,
'69-0', '33-1', '30-0', '41-8', '44-5', '2-13', '1-42', '26-1', '4-18', '13-16' ,

]
all_82_zl = [
'0-0', '0-1', '1-0', '0-2', '2-0', '0-4', '4-0', '1-1', '0-5', '2-1' ,
'5-0', '1-2', '0-8', '2-2', '8-0', '1-4', '4-1', '2-4', '9-0', '1-5' ,
'5-1', '4-2', '0-12', '2-5', '1-8', '12-0', '5-2', '8-1', '4-4', '13-0' ,
'15-0', '2-8', '1-9', '9-1', '8-2', '5-4', '4-5', '0-18', '2-9', '0-21' ,
'18-0', '9-2', '12-1', '5-5', '0-24', '4-8', '1-13', '20-0', '8-4', '22-0' ,
'2-12', '13-1', '24-0', '0-25', '15-1', '5-8', '4-9', '12-2', '9-4', '8-5' ,
'25-0', '13-2', '26-0', '1-18', '15-2', '5-9', '4-12', '0-30', '18-1', '12-4' ,
'9-5', '1-21', '8-8', '20-1', '4-13', '22-1', '4-16', '30-0', '13-4', '5-12' ,
'15-4', '24-1', '33-0', '18-2', '34-0', '2-21', '8-9', '35-0', '1-25', '9-8' ,
'12-5', '37-0', '20-2', '5-16', '22-2', '13-5', '25-1', '26-1', '24-2', '15-5' ,
'2-25', '39-0', '8-12', '2-26', '9-9', '18-4', '28-1', '12-8', '41-0', '0-45' ,
'4-21', '13-8', '25-2', '20-4', '22-4', '4-24', '26-2', '5-18', '15-8', '30-1' ,
'9-12', '44-0', '12-9', '28-2', '45-0', '33-1', '18-5', '2-30', '46-0', '34-1' ,
'13-9', '9-13', '9-16', '20-5', '22-5', '50-0', '30-2', '25-4', '15-9', '8-18' ,
'24-5', '12-12', '33-2', '18-8', '34-2', '35-2', '13-12', '41-1', '37-2', '22-8' ,
'56-0', '25-5', '26-5', '30-4', '18-9', '39-2', '13-16', '59-0', '33-4', '28-5' ,
'41-2', '35-4', '20-9', '22-9', '25-8', '65-0', '26-8', '24-9', '30-5', '12-18' ,
'44-2', '33-5', '45-2', '34-5', '35-5', '46-2', '12-20', '69-0', '37-5', '26-9' ,
'50-2', '51-2', '39-5', '54-2', '41-5', '56-2', '58-2', '34-9', '18-20', '59-2' ,
'44-5', '45-5', '60-2', '41-8', '46-5', '64-2', '65-2', '33-12', '50-5', '51-5' ,
]
list1 = all_82_eli
list2 = all_82_zl
common_elements = [item for item in list1 if item in list2]
only_in_list1 = [item for item in list1 if item not in list2]
only_in_list2 = [item for item in list2 if item not in list1]
unique_elements = only_in_list1 + only_in_list2

print(f"_state_all ({num_state}/{truc_tot_2}): \nOnly in Eli:", len(only_in_list1), only_in_list1)
print("Only in ZL:", len(only_in_list2), only_in_list2)

_state_all(len=200):
Only in Eli: 4 ['0-9', '2-13', '1-42', '4-18']
Only in ZL: 4 ['8-8', '33-4', '12-18', '18-20']

### Shortest path

In [43]:
# Find shortest path for each node
pool = Pool(processes=150)
shortest_path = {}
rabi_df["path"] = ""
rabi_df["path_len"] = 1.0
for idx, path in tqdm(pool.imap_unordered(shortest_path_to_core, hspace_full),
                total=truc_tot):
    shortest_path[idx[0]] = path
    rabi_df.at[idx, "path"] = path[1]
    rabi_df.at[idx, "path_len"] = np.exp(-path[0])

df_short = rabi_df.sort_values("path_len", ascending=False)
print('shortest_path:')
df_short.iloc[:30]

  0%|          | 0/1000 [00:00<?, ?it/s]FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '(3.959674672888022e-05-0j)' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
 50%|█████     | 500/1000 [00:06<00:06, 79.67it/s]

shortest_path:

,order,i,path,path_len
i,,,,
8-2,37,8-2,"2-2,8-2",1.000000e+00-0.000000e+ 00j
0-0,0,0-0,0-0,1.000000e+00+0.000000e+ 00j
2-2,13,2-2,2-2,1.000000e+00+0.000000e+ 00j
0-2,3,0-2,0-2,1.000000e+00+0.000000e+ 00j
2-0,4,2-0,2-0,1.000000e+00+0.000000e+ 00j
12-2,64,12-2,"2-2,8-2,12-2",6.577152e-05-0.000000e+ 00j
1-2,11,1-2,"0-2,1-2",4.369682e-05-0.000000e+ 00j
1-0,2,1-0,"0-0,1-0",3.959675e-05-0.000000e+ 00j
5-2,27,5-2,"2-2,5-2",3.553933e-05-0.000000e+ 00j
5-0,10,5-0,"2-0,5-0",2.842682e-05-0.000000e+ 00j
4-9,63,4-9,"2-2,8-2,4-9",1.534777e-05-0.000000e+ 00j
8-5,68,8-5,"2-2,8-2,8-5",1.221508e-06-0.000000e+ 00j
2-1,9,2-1,"2-0,2-1",1.220351e-06-0.000000e+ 00j
22-2,117,22-2,"2-2,8-2,22-2",9.096254e-07-0.000000e+ 00j
9-2,46,9-2,"2-2,8-2,9-2",4.265228e-07-0.000000e+ 00j
0-1,1,0-1,"0-0,0-1",3.948840e-07-0.000000e+ 00j
5-8,62,5-8,"2-2,8-2,5-8",2.330487e-07-0.000000e+ 00j
2-5,24,2-5,"2-2,2-5",2.246309e-07-0.000000e+ 00j
5-5,48,5-5,"2-2,8-2,5-5",1.603410e-07-0.000000e+ 00j
34-2,202,34-2,"2-2,8-2,34-2",1.306697e-07-0.000000e+ 00j
8-0,14,8-0,"2-0,8-0",1.083116e-07-0.000000e+ 00j
0-5,8,0-5,"0-2,0-5",9.579649e-08-0.000000e+ 00j
13-2,70,13-2,"2-2,8-2,13-2",6.045522e-08-0.000000e+ 00j
1-4,15,1-4,"2-0,1-4",3.012744e-08-0.000000e+ 00j
30-2,190,30-2,"2-2,8-2,30-2",1.368135e-08-0.000000e+ 00j
20-5,184,20-5,"2-2,8-2,20-5",7.841163e-09-0.000000e+ 00j
15-5,123,15-5,"2-2,8-2,15-5",4.686218e-09-0.000000e+ 00j
4-2,22,4-2,"0-2,1-2,4-2",4.628945e-09-0.000000e+ 00j
15-0,33,15-0,"2-0,15-0",3.074781e-09-0.000000e+ 00j
15-2,73,15-2,"2-2,15-2",2.996167e-09-0.000000e+ 00j

In [48]:
num_state = 100
df_short_truc = df_short.iloc[:num_state].sort_values("order", ascending=True)
print('state_short :')
data = df_short_truc['i']
for i in range(0, len(data), dim):  # Step size of 10
    print(", ".join(f"'{x}'" for x in data[i:i + dim]), ',')

index_all = [hspace_full.index(i) for i in df_short_truc['i']]
print(index_all)

state_short :
'0-0', '0-1', '1-0', '0-2', '2-0', '4-0', '1-1', '0-5', '2-1', '5-0' ,
'1-2', '0-8', '2-2', '8-0', '1-4', '4-1', '2-4', '9-0', '1-5', '5-1' ,
'4-2', '2-5', '1-8', '12-0', '5-2', '8-1', '4-4', '13-0', '15-0', '9-1' ,
'8-2', '5-4', '4-5', '0-21', '18-0', '9-2', '12-1', '5-5', '4-8', '1-13' ,
'20-0', '8-4', '2-12', '15-1', '5-8', '4-9', '12-2', '9-4', '8-5', '25-0' ,
'13-2', '26-0', '1-18', '15-2', '5-9', '4-12', '18-1', '9-5', '5-12', '15-4' ,
'18-2', '2-21', '8-9', '1-25', '9-8', '12-5', '20-2', '5-16', '22-2', '13-5' ,
'24-2', '15-5', '9-9', '18-4', '12-8', '25-2', '26-2', '9-12', '12-9', '45-0' ,
'18-5', '13-9', '20-5', '22-5', '30-2', '25-4', '15-9', '33-2', '34-2', '35-2' ,
'37-2', '25-5', '26-5', '30-5', '44-2', '45-2', '50-2', '56-2', '45-5', '64-2' ,
[0, 1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 18, 19, 20, 21, 22, 24, 25, 26, 27, 30, 31, 32, 33, 36, 37, 38, 39, 44, 45, 46, 47, 48, 50, 51, 52, 53, 56, 60, 62, 63, 64, 66, 68, 69, 70, 71, 72, 73, 75, 76, 79, 81, 97, 98, 102, 104, 105, 107, 108, 111, 115, 116, 117, 118, 122, 123, 129, 130, 134, 142, 149, 157, 160, 162, 164, 176, 184, 186, 190, 191, 192, 198, 202, 205, 215, 226, 230, 283, 293, 298, 336, 398, 440, 463]

In [50]:
short_82_eli = [
'0-0', '0-2', '2-2', '8-2', '2-0', '12-2', '1-2', '1-0', '5-2', '5-0' ,
'4-9', '8-5', '2-1', '22-2', '0-1', '9-2', '5-8', '2-5', '5-5', '34-2' ,
'8-0', '0-5', '13-2', '1-4', '30-2', '20-5', '4-2', '15-5', '15-0', '15-2' ,
'1-1', '8-9', '26-5', '24-2', '26-2', '9-0', '20-2', '25-2', '4-5', '4-0' ,
'5-1', '12-5', '12-0', '18-2', '9-5', '1-5', '13-0', '37-2', '35-2', '9-4' ,
'8-1', '20-0', '4-1', '9-1', '13-9', '33-2', '1-13', '18-0', '18-5', '9-9' ,
'12-8', '5-4', '0-21', '9-8', '1-8', '26-0', '5-12', '5-16', '15-1', '22-5' ,
'25-4', '1-25', '4-4', '5-9', '2-4', '18-4', '9-12', '15-4', '1-18', '64-2' ,
'45-0', '12-9', '13-5', '4-8', '44-2', '8-4', '45-5', '25-5', '2-12', '12-1' ,
'0-8', '50-2', '4-12', '45-2', '2-21', '18-1', '15-9', '25-0', '1-9', '2-8' ,
]
list1 = short_82_eli
list2 = df_short_truc['i']
common_elements = [item for item in list1 if item in list2]
only_in_list1 = [item for item in list1 if item not in list2]
only_in_list2 = [item for item in list2 if item not in list1]
unique_elements = only_in_list1 + only_in_list2

print(f"_state_short ({num_state}/{truc_tot_2}): \nOnly in Eli:", len(only_in_list1), only_in_list1)
print("Only in ZL:", len(only_in_list2), only_in_list2)

_state_short (100/500):
Only in Eli: 2 ['1-9', '2-8']
Only in ZL: 2 ['30-5', '56-2']

In [26]:
=

SyntaxError: invalid syntax (1763773627.py, line 1)

In [ ]:
hspace_index = [hspace_full.index(i) for i in logi_state]
print('index_state :')
dim = 10
data = hspace_full
for i in range(0, len(data), dim):  # Step size of 10
    print(i,", ".join(f"'{x}'" for x in data[i:i + dim]), ',')

if charge_pick==False:
    thresh = 1e-2
    for s in hspace_index:
        for i in range(truc_tot):
            if np.abs(n_theta0_dress[s, i]) > thresh and i not in hspace_index:
                hspace_index.append(i)
    hspace_index.sort()
    print('threshold=', thresh)
    print('truncation_tot =', truc_tot, ', truncation_2nd_tot =', len(hspace_index))
    print('index_state after charge pick :')

    hspace_tot = np.array(hspace_full)[hspace_index]
    dim = 10
    data = hspace_tot
    for i in range(0, len(data), dim):  # Step size of 10
        print(", ".join(f"'{x}'" for x in data[i:i + dim]), ',')

index_state :
0 '0-0', '0-1', '1-0', '0-2', '2-0', '0-4', '4-0', '1-1', '0-5', '2-1' ,
10 '5-0', '1-2', '0-8', '2-2', '8-0', '1-4', '4-1', '0-9', '2-4', '9-0' ,
20 '1-5', '5-1', '4-2', '0-12', '2-5', '1-8', '12-0', '5-2', '0-13', '0-16' ,
30 '8-1', '4-4', '13-0', '15-0', '2-8', '1-9', '9-1', '8-2', '5-4', '4-5' ,
40 '0-18', '2-9', '1-12', '0-20', '0-21', '18-0', '9-2', '12-1', '5-5', '0-24' ,
50 '4-8', '1-13', '20-0', '8-4', '1-16', '22-0', '2-12', '13-1', '24-0', '0-25' ,
60 '15-1', '0-26', '5-8', '4-9', '12-2', '2-13', '9-4', '2-16', '8-5', '25-0' ,
70 '13-2', '26-0', '1-18', '15-2', '0-28', '5-9', '4-12', '28-0', '0-30', '18-1' ,
80 '12-4', '9-5', '1-20', '1-21', '0-33', '8-8', '0-34', '0-35', '1-24', '2-18' ,
90 '0-36', '20-1', '4-13', '22-1', '4-16', '30-0', '13-4', '5-12', '15-4', '24-1' ,
100 '33-0', '2-20', '18-2', '34-0', '2-21', '8-9', '35-0', '1-25', '9-8', '1-26' ,
110 '0-39', '12-5', '2-24', '37-0', '5-13', '20-2', '5-16', '22-2', '13-5', '25-1' ,
120 '0-42', '26-1', '24-2', '15-5', '4-18', '2-25', '39-0', '8-12', '2-26', '9-9' ,
130 '18-4', '28-1', '1-28', '0-44', '12-8', '41-0', '1-30', '4-20', '0-45', '4-21' ,
140 '0-46', '13-8', '25-2', '1-33', '8-13', '20-4', '8-16', '22-4', '4-24', '26-2' ,
150 '5-18', '1-34', '1-35', '15-8', '30-1', '1-36', '2-28', '9-12', '24-4', '44-0' ,
160 '12-9', '28-2', '45-0', '33-1', '18-5', '2-30', '0-52', '0-53', '46-0', '34-1' ,
170 '5-20', '35-1', '4-25', '5-21', '4-26', '2-33', '13-9', '9-13', '1-39', '5-24' ,
180 '37-1', '9-16', '2-34', '2-35', '20-5', '0-54', '22-5', '2-36', '50-0', '51-0' ,
190 '30-2', '25-4', '15-9', '0-55', '26-4', '8-18', '24-5', '12-12', '33-2', '0-57' ,
200 '39-1', '18-8', '34-2', '1-42', '5-25', '35-2', '54-0', '28-4', '5-26', '0-59' ,
210 '2-39', '4-28', '8-20', '13-12', '41-1', '37-2', '0-60', '8-21', '12-16', '1-44' ,
220 '20-8', '4-30', '12-13', '22-8', '56-0', '8-24', '25-5', '1-45', '15-12', '9-18' ,
230 '26-5', '1-46', '4-33', '0-64', '24-8', '30-4', '2-42', '58-0', '13-13', '4-34' ,
240 '4-35', '18-9', '39-2', '0-65', '4-36', '13-16', '59-0', '33-4', '28-5', '5-28' ,
250 '15-13', '44-1', '34-4', '60-0', '9-20', '8-25', '45-1', '2-44', '41-2', '35-4' ,
260 '15-16', '9-21', '46-1', '5-30', '8-26', '20-9', '1-52', '1-53', '22-9', '2-45' ,
270 '64-0', '9-24', '0-66', '37-4', '2-46', '25-8', '5-33', '4-39', '0-68', '65-0' ,
280 '26-8', '0-70', '24-9', '30-5', '5-34', '5-35', '12-18', '50-1', '51-1', '1-54' ,
290 '5-36', '18-12', '28-8', '44-2', '1-55', '0-73', '33-5', '39-4', '45-2', '9-25' ,
300 '0-76', '34-5', '35-5', '2-52', '2-53', '4-42', '46-2', '12-20', '13-18', '0-77' ,
310 '9-26', '20-12', '22-12', '1-57', '66-0', '12-21', '54-1', '8-28', '18-13', '69-0' ,
320 '41-4', '25-9', '37-5', '70-0', '0-78', '12-24', '1-59', '5-39', '8-30', '18-16' ,
330 '15-18', '26-9', '4-44', '2-54', '24-12', '1-60', '50-2', '56-1', '74-0', '51-2' ,
340 '30-8', '13-20', '0-81', '13-21', '75-0', '8-33', '4-45', '20-13', '2-55', '8-34' ,
350 '22-13', '28-9', '77-0', '8-35', '13-24', '20-16', '33-8', '15-20', '4-46', '8-36' ,
360 '39-5', '58-1', '15-21', '22-16', '2-57', '34-8', '5-42', '35-8', '1-64', '12-26' ,
370 '12-25', '59-1', '9-28', '54-2', '24-13', '1-65', '44-4', '45-4', '24-16', '2-59' ,
380 '15-24', '0-82', '41-5', '79-0', '60-1', '46-4', '9-30', '0-83', '37-8', '81-0' ,
390 '25-12', '2-60', '5-44', '26-12', '0-86', '4-52', '4-53', '30-9', '56-2', '13-25' ,
400 '64-1', '8-39', '9-33', '5-45', '13-26', '18-18', '9-34', '51-4', '1-66', '9-35' ,
410 '28-12', '50-4', '5-46', '15-25', '9-36', '65-1', '2-64', '33-9', '58-2', '25-13' ,
420 '1-68', '15-26', '39-8', '35-9', '34-9', '4-54', '1-70', '2-65', '25-16', '26-13' ,
430 '18-20', '59-2', '0-89', '20-18', '0-90', '84-0', '12-28', '44-5', '26-16', '18-21' ,
440 '45-5', '4-55', '85-0', '60-2', '22-18', '41-8', '46-5', '8-42', '37-9', '54-4' ,
450 '1-73', '28-13', '12-30', '18-24', '86-0', '5-52', '66-1', '5-53', '1-76', '4-57' ,
460 '28-16', '24-18', '30-12', '64-2', '1-77', '9-39', '0-92', '69-1', '0-93', '12-33' ,
470 '20-21', '2-66', '20-20', '70-1', '13-28', '4-59', '65-2', '33-12', '56-4', '8-44' ,
480 '2-68', '20-24', '12-35', '12-34', '1-78', '22-20', '50-5', '51-5', '2-70', '13-30' ,
490 '34-12', '4-60', '39-9', '74-1', '5-54', '35-12', '15-28', '12-36', '8-45', '75-1' ,
500 '24-21', '89-0', '90-0', '24-20', '8-46', '1-81', '22-24', '18-25', '0-97', '77-1' ,
510 '0-98', '30-13', '58-4', '44-8', '13-33', '5-55', '22-21', '41-9', '0-100', '9-42' ,
520 '45-8', '2-73', '15-30', '18-26', '37-12', '59-4', '2-76', '92-0', '93-0', '13-34' ,
530 '13-35', '24-24', '30-16', '4-64', '25-18', '54-5', '5-57', '46-8', '2-77', '66-2' ,
540 '13-36', '0-102', '0-103', '33-13', '4-65', '26-18', '60-4', '15-33', '34-13', '69-2' ,
550 '20-25', '35-13', '5-59', '79-1', '70-2', '22-25', '9-44', '81-1', '2-78', '12-39' ,
560 '33-16', '15-35', '8-52', '15-34', '1-82', '8-53', '35-16', '15-36', '34-16', '64-4' ,
570 '1-83', '56-5', '51-8', '5-60', '20-26', '28-18', '50-8', '22-26', '74-2', '25-20' ,
580 '25-21', '9-45', '37-13', '98-0', '99-0', '39-12', '2-81', '75-2', '0-105', '9-46' ,
590 '1-86', '26-21', '37-16', '0-106', '65-4', '26-20', '24-25', '100-0', '77-2', '4-66' ,
600 '24-26', '44-9', '13-39', '58-5', '8-54', '45-9', '25-24', '102-0', '101-0', '18-28' ,
610 '46-9', '41-12', '4-68', '5-64', '4-70', '26-24', '12-42', '28-20', '59-5', '54-8' ,
620 '15-39', '28-21', '5-65', '18-30', '8-55', '84-1', '0-109', '39-13', '60-5', '30-18' ,
630 '2-82', '1-89', '79-2', '39-16', '85-1', '1-90', '81-2', '8-57', '66-4', '2-83' ,
640 '28-24', '9-53', '9-52', '18-33', '0-110', '0-112', '4-73', '12-44', '20-28', '86-1' ,
650 '56-8', '64-5', '33-18', '69-4', '13-42', '4-76', '105-0', '25-25', '106-0', '22-28' ,
660 '51-9', '18-35', '18-34', '41-13', '2-86', '50-9', '70-4', '8-59', '34-18', '4-77' ,
670 '20-30', '25-26', '41-16', '12-45', '35-18', '18-36', '15-42', '26-25', '22-30', '5-66' ,
680 '65-5', '30-21', '1-93', '1-92', '26-26', '8-60', '9-54', '44-12', '74-4', '45-12' ,
690 '30-20', '24-28', '4-78', '12-46', '58-8', '75-4', '5-68', '13-44', '30-24', '0-114' ,
700 '20-33', '5-70', '20-34', '20-35', '46-12', '37-18', '34-21', '77-4', '28-25', '89-1' ,
710 '35-21', '54-9', '90-1', '9-55', '22-33', '59-8', '4-81', '28-26', '109-0', '24-30' ,
720 '13-45', '2-89', '84-2', '0-116', '2-90', '20-36', '33-20', '60-8', '8-64', '13-46' ,
730 '110-0', '15-44', '85-2', '111-0', '9-57', '1-97', '35-20', '1-98', '34-20', '22-36' ,
740 '8-65', '5-73', '92-1', '93-1', '22-35', '66-5', '22-34', '1-100', '50-12', '24-35' ,
750 '12-52', '51-12', '44-13', '24-33', '5-76', '86-2', '18-39', '12-53', '56-9', '45-13' ,
760 '35-24', '15-45', '79-4', '5-77', '9-59', '64-8', '69-5', '46-13', '37-20', '0-121' ,
770 '44-16', '15-46', '33-24', '70-5', '24-36', '81-4', '24-34', '34-24', '39-18', '1-102' ,
780 '2-92', '26-34', '1-103', '2-93', '25-28', '37-21', '45-16', '46-16', '9-60', '65-8' ,
790 '30-25', '4-82', '5-78', '26-28', '74-5', '115-0', '4-83', '58-9', '25-30', '37-24' ,
800 '30-26', '75-5', '12-54', '13-52', '13-53', '98-1', '99-1', '20-39', '116-0', '26-30' ,
810 '8-66', '41-18', '89-2', '22-39', '54-12', '4-86', '90-2', '5-81', '59-9', '33-25' ,
820 '77-5', '34-25', '50-13', '51-13', '18-42', '100-1', '39-20', '2-97', '28-28', '12-55' ,
830 '2-98', '1-105', '8-68', '0-123', '39-21', '9-64', '60-9', '0-124', '25-33', '1-106' ,
840 '35-25', '2-100', '8-70', '102-1', '101-1', '0-125', '25-34', '25-35', '15-53', '35-26' ,
850 '26-33', '24-39', '15-52', '92-2', '93-2', '66-8', '50-16', '84-4', '28-30', '33-26' ,
860 '9-65', '51-16', '34-26', '12-57', '0-128', '13-54', '56-12', '121-0', '39-24', '25-36' ,
870 '18-44', '41-20', '2-102', '64-9', '2-103', '85-4', '41-21', '0-129', '37-25', '69-8' ,
880 '79-5', '26-36', '20-42', '8-73', '26-35', '70-8', '12-59', '12-76', '81-5', '37-26' ,
890 '4-89', '4-90', '13-55', '54-13', '18-45', '22-42', '86-4', '28-33', '1-109', '8-76' ,
900 '5-82', '15-54', '41-24', '0-131', '65-9', '5-83', '8-77', '12-60', '44-18', '28-34' ,
910 '18-46', '58-12', '54-16', '28-35', '105-1', '45-18', '74-8', '106-1', '30-28', '13-57' ,
920 '1-110', '1-112', '98-2', '99-2', '28-36', '0-132', '75-8', '24-42', '9-66', '5-86' ,
930 '46-18', '123-0', '30-30', '15-55', '2-105', '8-78', '20-44', '20-45', '124-0', '77-8' ,
940 '59-12', '2-106', '25-39', '100-2', '56-13', '13-59', '9-68', '4-92', '127-0', '60-12' ,
950 '39-25', '4-93', '33-30', '9-70', '15-57', '22-44', '33-28', '39-26', '102-2', '101-2' ,
960 '89-4', '128-0', '12-64', '20-46', '45-21', '26-39', '44-21', '90-4', '34-28', '56-16' ,
970 '0-135', '34-30', '30-34', '13-60', '35-28', '30-35', '8-81', '35-30', '12-65', '66-9' ,
980 '129-0', '15-59', '84-5', '50-18', '41-25', '1-114', '0-136', '51-18', '24-44', '18-53' ,
990 '18-52', '44-20', '58-13', '64-12', '109-1', '22-45', '2-109', '79-8', '85-5', '41-26' ,

In [ ]:
if truc_tot < 30:
    nx.draw(G, pos=nx.shell_layout(G), with_labels=True)
print(G['0-0']['1-0'])
qt.Qobj(population_rate_log)

{'weight': (7.60517024528502-0j)}

Quantum object: dims = [[1000], [1000]], shape = (1000, 1000), type = oper, isherm = False
Qobj data =
[[ 0.         10.04754427  7.60517025 ... 42.40559133  0.
   0.        ]
 [ 0.          0.          0.         ...  0.         36.51149341
  45.17936135]
 [ 0.          0.          0.         ...  0.         37.47918684
  41.75901104]
 ...
 [ 0.          0.          0.         ...  0.         13.57799005
  15.07190484]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]]

In [ ]:
print(shortest_path_to_core('1-0'))
print(all_path_to_core('0-4'))
print(all_path_to_core('0-1'))
target = '0-4'
source = '0-0'
paths = nx.all_simple_paths(G, source=source, target=target, cutoff=cutoff)
weight_tot = sum([np.exp(- nx.path_weight(G, path=path, weight='weight'))
                   for path in paths])
print(weight_tot)
for path in nx.all_simple_paths(G, source=source, target=target, cutoff=cutoff):
    print(path)

(1.210603091631031e-09+0j)
['0-0', '0-1', '0-4']
['0-0', '1-0', '0-4']

In [ ]:
cnot_80 = ['0-0', '0-1', '1-0', '0-2', '2-0', '4-0', '1-1', '0-5', '2-1', '5-0' ,
'1-2', '0-8', '2-2', '8-0', '1-4', '4-1', '0-9', '2-4', '9-0', '1-5' ,
'5-1', '4-2', '2-5', '1-8', '12-0', '5-2', '0-13', '8-1', '4-4', '13-0' ,
'15-0', '2-8', '1-9', '9-1', '8-2', '5-4', '4-5', '0-18', '1-12', '0-20' ,
'0-21', '18-0', '9-2', '12-1', '5-5', '4-8', '1-13', '20-0', '8-4', '22-0' ,
'13-1', '24-0', '15-1', '5-8', '4-9', '12-2', '2-13', '9-4', '8-5', '25-0' ,
'13-2', '26-0', '15-2', '5-9', '4-12', '28-0', '0-30', '18-1', '12-4', '9-5' ,
'1-20', '1-21', '8-8', '0-35', '0-36', '20-1', '4-13', '22-1', '30-0', '13-4' ,
'5-12', '15-4', '24-1', '33-0', '18-2', '34-0', '2-21', '8-9', '35-0', '1-25' ,
'9-8', '12-5', '37-0', '20-2', '22-2', '13-5', '25-1', '26-1', '24-2', '15-5' ,
'39-0', '9-9', '18-4', '28-1', '12-8', '41-0', '4-21', '13-8', '25-2', '8-13' ,
'20-4', '8-16', '22-4', '4-24', '26-2', '5-18', '15-8', '30-1', '9-12', '24-4' ,
'44-0', '12-9', '28-2', '45-0', '33-1', '18-5', '2-30', '46-0', '34-1', '35-1' ,
'5-21', '13-9', '9-13', '37-1', '20-5', '50-0', '51-0', '30-2', '25-4', '15-9' ,
'26-4', '24-5', '33-2', '39-1', '34-2', '35-2', '54-0', '28-4', '41-1', '37-2' ,
'22-8', '56-0', '26-5', '30-4', '58-0', '18-9', '39-2', '59-0', '33-4', '15-13' ,
'44-1', '34-4', '60-0', '45-1', '41-2', '35-4', '46-1', '64-0', '37-4', '65-0' ,
'26-8', '50-1', '51-1', '44-2', '33-5', '45-2', '34-5', '35-5', '69-0', '70-0' ,
'15-18', '50-2', '74-0', '75-0', '77-0', '33-8', '58-1', '34-8', '44-4', '41-5' ,
'60-1', '46-4', '81-0', '56-2', '65-1', '59-2', '60-2', '74-1', '98-0', '123-0' ,
]

[0, 1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 18, 19, 20, 21, 22, 24, 25, 26, 27, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 55, 56, 57, 58, 59, 60, 62, 63, 64, 66, 68, 69, 70, 71, 72, 73, 75, 76, 78, 79, 80, 81, 82, 83, 85, 87, 90, 91, 92, 95, 96, 97, 98, 100, 102, 103, 104, 105, 106, 107, 108, 111, 115, 116, 117, 118, 121, 122, 123, 125, 126, 129, 130, 134, 135, 138, 139, 141, 142, 145, 147, 148, 149, 150, 153, 157, 158, 159, 160, 161, 162, 163, 164, 165, 168, 171, 176, 177, 183, 184, 186, 187, 189, 190, 191, 192, 195, 196, 197, 198, 201, 202, 203, 205, 213, 214, 215, 226, 230, 235, 241, 242, 248, 258, 259, 265, 268, 275, 280, 282, 283, 286, 293, 296, 297, 298, 301, 302, 306, 313, 320, 322, 331, 336, 339, 361, 373, 377, 398, 401, 418, 424, 431, 437, 440, 443, 444, 446, 463, 476, 486, 487, 549, 554, 578, 587, 598, 603, 611, 636, 651, 680, 922]

In [ ]:
aa = df_all_truc['i'].to_numpy().tolist()
index = [hspace_full.index(i) for i in aa]
index

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 72,
 73,
 75,
 76,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 94,
 97,
 98,
 99,
 101,
 102,
 104,
 105,
 107,
 108,
 109,
 110,
 111,
 112,
 114,
 116,
 117,
 120,
 123,
 125,
 127,
 128,
 129,
 133,
 136,
 138,
 140,
 143,
 147,
 148,
 150,
 151,
 153,
 156,
 157,
 158,
 160,
 164,
 165,
 166,
 167,
 170,
 172,
 173,
 175,
 177,
 178,
 179,
 181,
 182,
 183,
 185,
 187,
 193,
 199,
 204,
 208,
 209,
 210,
 227,
 236,
 243,
 254,
 257,
 260,
 263,
 265,
 269,
 271,
 274,
 276,
 278,
 284,
 285,
 290,
 295,
 303,
 304,
 310,
 324,
 327,
 329,
 332,
 333,
 348,
 364,
 366,
 379,
 387,
 391,
 392,
 401,
 402,
 403,
 406,
 409,
 412,
 416,
 427,
 455,
 457,
 471,
 480,
 515,
 521,
 526,
 552,
 556,
 622,
 639,
 696,
 905]

In [ ]:
df_all_truc = df_all.iloc[:200].sort_values("order", ascending=True)
print('state_all :')
data = df_all_truc['i']
for i in range(0, len(data), dim):  # Step size of 10
    print(", ".join(f"'{x}'" for x in data[i:i + dim]), ',')

state_all :
'0-0', '0-1', '1-0', '0-2', '2-0', '0-4', '4-0', '1-1', '0-5', '2-1' ,
'5-0', '1-2', '0-8', '2-2', '8-0', '1-4', '4-1', '0-9', '2-4', '9-0' ,
'1-5', '5-1', '4-2', '0-12', '2-5', '1-8', '12-0', '5-2', '0-13', '0-16' ,
'8-1', '4-4', '13-0', '15-0', '2-8', '1-9', '9-1', '8-2', '5-4', '4-5' ,
'0-18', '2-9', '1-12', '0-20', '0-21', '18-0', '9-2', '12-1', '5-5', '0-24' ,
'4-8', '1-13', '20-0', '8-4', '1-16', '22-0', '2-12', '13-1', '24-0', '0-25' ,
'15-1', '0-26', '5-8', '4-9', '12-2', '2-13', '9-4', '2-16', '8-5', '25-0' ,
'13-2', '1-18', '15-2', '5-9', '4-12', '0-30', '18-1', '12-4', '9-5', '1-20' ,
'1-21', '0-33', '8-8', '0-34', '0-35', '1-24', '2-18', '0-36', '4-16', '5-12' ,
'15-4', '24-1', '2-20', '18-2', '2-21', '8-9', '1-25', '9-8', '1-26', '0-39' ,
'12-5', '2-24', '5-13', '5-16', '22-2', '0-42', '15-5', '2-25', '8-12', '2-26' ,
'9-9', '0-44', '1-30', '0-45', '0-46', '1-33', '22-4', '4-24', '5-18', '1-34' ,
'15-8', '2-28', '9-12', '24-4', '12-9', '18-5', '2-30', '0-52', '0-53', '5-20' ,
'4-25', '5-21', '2-33', '9-13', '1-39', '5-24', '9-16', '2-34', '2-35', '0-54' ,
'2-36', '0-55', '0-57', '5-25', '5-26', '0-59', '2-39', '1-45', '2-42', '0-65' ,
'9-20', '2-44', '15-16', '5-30', '20-9', '2-45', '9-24', '2-46', '5-33', '0-68' ,
'5-34', '5-35', '5-36', '0-73', '2-52', '2-53', '9-26', '0-78', '5-39', '18-16' ,
'4-44', '2-54', '2-55', '2-57', '5-42', '2-59', '0-83', '2-60', '5-44', '8-39' ,
'9-33', '5-45', '9-34', '9-35', '5-46', '2-64', '2-65', '5-52', '5-53', '2-66' ,
'2-68', '5-55', '2-73', '2-76', '5-59', '9-44', '5-65', '2-83', '5-68', '5-83' ,

In [ ]:
print('cutoff=', cutoff)
target = '5-2'
print(shortest_path_to_core(target))
idx, path = all_path_to_core(target)
for i in path[1]:
    print(i)

cutoff= 2
('5-2', ((1.1144374429708779+0j), '2-2,5-2'))
['0-0', '5-2']
['0-2', '5-2']
['2-0', '5-2']
['2-2', '5-2']
['5-0', '2-2', '5-2']
['5-0', '0-9', '5-2']
['5-0', '2-4', '5-2']
['5-0', '9-0', '5-2']
['5-0', '1-5', '5-2']
['5-0', '5-1', '5-2']
['5-0', '4-2', '5-2']
['5-0', '0-12', '5-2']
['5-0', '1-8', '5-2']
['5-0', '12-0', '5-2']

In [ ]:
print('cutoff=', cutoff)
target = '5-2'
print(shortest_path_to_core(target))
idx, path = all_path_to_core(target)
for i in path[1]:
    print(i)

cutoff= 2
('5-2', ((1.1144374429708779+0j), '2-2,5-2'))
['0-0', '5-2']
['0-2', '5-2']
['2-0', '5-2']
['2-2', '5-2']
['5-0', '2-2', '5-2']
['5-0', '0-9', '5-2']
['5-0', '2-4', '5-2']
['5-0', '9-0', '5-2']
['5-0', '1-5', '5-2']
['5-0', '5-1', '5-2']
['5-0', '4-2', '5-2']
['5-0', '0-12', '5-2']
['5-0', '1-8', '5-2']
['5-0', '12-0', '5-2']

In [ ]:
# Find shortest path for each node
pool = Pool(processes=150)
shortest_path = {}
rabi_df["path"] = ""
rabi_df["path_len"] = 0.0
rabi_df["degree"] = -1
for idx, path in tqdm(pool.imap_unordered(shortest_path_to_core, hspace_full),
                total=truc_tot):
    shortest_path[idx[0]] = path
    rabi_df.at[idx, "path"] = path[1]
    rabi_df.at[idx, "path_len"] = np.exp(-path[0])
    rabi_df.at[idx, "degree"] = path[1].count(",")

# print(population_rate[index_state.index('0-0'), index_state.index('0-1')] *
#       population_rate[index_state.index('0-1'), index_state.index('0-4')])
# print(population_rate[index_state.index('0-0'), index_state.index('1-0')] *
#       population_rate[index_state.index('1-0'), index_state.index('0-4')])
print(rabi_df.sort_values("path_len", ascending=False).iloc[:15])
# qt.Qobj(population_rate[:10,:10])

  0%|          | 0/1000 [00:00<?, ?it/s]FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '(0.03355836019110092-0j)' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
100%|██████████| 1000/1000 [00:03<00:00, 258.22it/s]

     order    i         path            path_len  degree
i
0-0      0  0-0          0-0  1.000000+0.000000j       0
2-2     13  2-2          2-2  1.000000+0.000000j       0
0-2      3  0-2          0-2  1.000000+0.000000j       0
2-0      4  2-0          2-0  1.000000+0.000000j       0
5-0     10  5-0      2-0,5-0  1.000000-0.000000j       1
5-2     27  5-2      2-2,5-2  0.328100-0.000000j       1
5-1     21  5-1  2-0,5-0,5-1  0.063630-0.000000j       2
0-1      1  0-1      0-0,0-1  0.033558-0.000000j       1
2-1      9  2-1      2-0,2-1  0.027706-0.000000j       1
1-0      2  1-0      0-0,1-0  0.022540-0.000000j       1
0-5      8  0-5      0-2,0-5  0.014840-0.000000j       1
2-5     24  2-5      2-2,2-5  0.013964-0.000000j       1
1-2     11  1-2      0-2,1-2  0.013392-0.000000j       1
4-0      6  4-0  0-0,0-1,4-0  0.007998-0.000000j       2
5-5     48  5-5  2-2,5-2,5-5  0.005663-0.000000j       2